#2 send receive files
ka11i0/BetterFilesharing pull request #26
Opened 2020-02-07 13:12 UTC by Froopas

Not tested!!!

2020-02-10 09:51 UTC, ka11i0 approved these changes
Approved to be tested

2020-02-11 09:30 UTC, CarlOsterberg requested changes
byt från id till ip rad 146

2020-02-11 09:31 UTC, marekp5 approved these changes

2020-02-11 09:32 UTC, marekp5 commented
> byt från id till ip rad 146

aa, det tycker jag med :)

2020-02-11 09:44 UTC, HectorNyblom approved these changes

2020-02-11 09:53 UTC, closed without merging